name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd backend
        npm install
    
    - name: Run tests
      run: |
        cd backend
        npm test
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://localhost:27017/carsharing_test
    
    - name: Run lint
      run: |
        cd backend
        npm run lint

  web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd web
        npm install
    
    - name: Run tests
      run: |
        cd web
        CI=true npm test -- --coverage --watchAll=false
    
    - name: Run lint
      run: |
        cd web
        npm run lint
    
    - name: Build application
      run: |
        cd web
        npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: web/build/

  mobile:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd mobile
        npm install
    
    - name: Check Expo project
      run: |
        cd mobile
        echo "Mobile project structure checked"
        echo "Package.json exists: $(test -f package.json && echo 'Yes' || echo 'No')"
        echo "Node modules installed: $(test -d node_modules && echo 'Yes' || echo 'No')"
    
    - name: Run lint (if available)
      run: |
        cd mobile
        npm run lint || echo "Lint not configured yet" 